// kitty-sentiment/frontend/src/pages/Login.tsx
import React, { useState } from 'react';
import { Form, Input, Button, Card, Alert } from 'antd';
import { UserOutlined, LockOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import { login } from '../api/api_auth';

const Login: React.FC = () => {
  const [form] = Form.useForm();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const navigate = useNavigate();

  const onFinish = async (values: any) => {
    setLoading(true);
    setError(null);
    try {
      const { data } = await login({
        username: values.username,
        password: values.password,
      });
      localStorage.setItem('token', data.token);
      navigate('/');
    } catch (err) {
      setError('网络错误，请稍后重试');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ 
      display: 'flex', 
      justifyContent: 'center', 
      alignItems: 'center', 
      minHeight: '100vh', 
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)'
    }}>
      <Card 
        style={{ 
          width: 400, 
          boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
          borderRadius: '8px'
        }}
      >
        <div style={{ textAlign: 'center', marginBottom: 24 }}>
          <h2 style={{ margin: 0, color: '#1890ff' }}>舆情监控系统</h2>
          <p style={{ color: '#666', marginTop: 8 }}>登录管理后台</p>
        </div>

        {error && (
          <Alert
            message={error}
            type="error"
            showIcon
            style={{ marginBottom: 16 }}
          />
        )}

        <Form
          form={form}
          name="login"
          onFinish={onFinish}
          initialValues={{ remember: true }}
          size="large"
        >
          <Form.Item
            name="username"
            rules={[{ required: true, message: '请输入用户名' }]}
          >
            <Input 
              prefix={<UserOutlined />} 
              placeholder="用户名" 
            />
          </Form.Item>

          <Form.Item
            name="password"
            rules={[{ required: true, message: '请输入密码' }]}
          >
            <Input.Password
              prefix={<LockOutlined />}
              placeholder="密码"
            />
          </Form.Item>

          <Form.Item>
            <Button 
              type="primary" 
              htmlType="submit" 
              loading={loading}
              style={{ width: '100%' }}
            >
              登录
            </Button>
          </Form.Item>
        </Form>

        <div style={{ textAlign: 'center', marginTop: 16 }}>
          <p style={{ color: '#999', fontSize: '12px' }}>
            测试账号：admin / 密码：admin
          </p>
        </div>
      </Card>
    </div>
  );
};

export default Login;

// frontend/packages/transcoder/src/views/Login.vue
<template>
  <div class="login-wrap">
    <a-card title="转码服务登录（AK/SK）" class="card">
      <a-form :model="form" layout="vertical" @finish="onSubmit">
        <a-form-item label="Access Key ID" name="accessKeyId" :rules="[{ required: true }]">
          <a-input v-model:value="form.accessKeyId" placeholder="AK..." />
        </a-form-item>
        <a-form-item label="Secret Key" name="secretKey" :rules="[{ required: true }]">
          <a-input-password v-model:value="form.secretKey" placeholder="SK..." />
        </a-form-item>
        <a-form-item>
          <a-button type="primary" html-type="submit" :loading="loading" block>登录</a-button>
        </a-form-item>
      </a-form>
    </a-card>
  </div>
</template>

<script setup>
import { reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { message } from 'ant-design-vue'
import { login } from '../api/auth_api'

const router = useRouter()
const loading = ref(false)
const form = reactive({ accessKeyId: '', secretKey: '' })

async function onSubmit() {
  try {
    loading.value = true
    const res = await login(form)
    localStorage.setItem('transcoder_token', res.token)
    message.success('登录成功')
    router.push('/')
  } catch (e) {
    message.error(e?.message || '登录失败')
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.login-wrap { display: flex; justify-content: center; align-items: center; min-height: 100vh; background: #f0f2f5; }
.card { width: 400px; }
</style>
